Repository eclipse/kiso-testing, pull requests merged in 2022-03, with the labels that each got.

#28 fix: wait for logger thread to quit gracefully before closing segger …
  CHANGELOG.md
  src/pykiso/lib/connectors/cc_rtt_segger.py
  tests/test_cc_rtt_segger.py
Labels: bug

#34 feat: update to new release 0.16.0
  CHANGELOG.md
  setup.py
  src/pykiso/__init__.py
Labels: documentation

#35 fix: qsize() not available for macos x
  tests/test_cc_proxy.py
  tests/test_proxy_auxiliary.py
Labels: good first issue

#36 docs[README.md]: Remove not maintained 'list of limitations' section
  README.md
Labels: documentation
